version: '3.1'

services:

    # rdf-oriented database
    graphdb:
      image: ontotext/graphdb:10.3.2
      ports:
        - 8000:7200
      environment:
        GDB_JAVA_OPTS: -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
      #volumes:
      #  - ./gd-data:/opt/graphdb/home
      networks:
        - gestbd_net


networks:
    gestbd_net:
      external: true

